---
apiVersion: v1
kind: Template
metadata:
  name: mysql-backup-s3-job-template
  annotations:
    description: 'Job for backing up MySQL data to Amazon S3'
objects:
  -
    apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-backup-s3-secret
    data:
      gpg_public_key: ${GPG_PUBLIC_KEY}
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: mysql-backup-s3
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: mysql-backup-s3
        spec:
          containers:
            - name: mysql-backup-s3
              image: 'docker.io/rhmap/backups:latest'
              command:
                - 'bash'
                - '-c'
                - '/opt/rh/scripts/mysql/backup-s3.sh ${MYSQL_HOST} ${MYSQL_USER} ${MYSQL_PASSWORD} ${AWS_S3_BUCKET_NAME} ${GPG_RECIPIENT}'
              volumeMounts:
                - name: mysql-backup-s3-secret-volume
                  mountPath: /opt/rh/secrets
                  readOnly: true
              env:
                - name: AWS_ACCESS_KEY_ID
                  value: ${AWS_ACCESS_KEY_ID}
                - name: AWS_SECRET_ACCESS_KEY
                  value: ${AWS_SECRET_ACCESS_KEY}
                - name: GPG_RECIPIENT
                  value: ${GPG_RECIPIENT}
                - name: GPG_PUBLIC_KEY
                  value: ${GPG_PUBLIC_KEY}
                - name: GPG_SECRET_KEY
                  value: ${GPG_SECRET_KEY}
                - name: GPG_TRUST_MODEL
                  value: ${GPG_TRUST_MODEL}
          volumes:
            - name: mysql-backup-s3-secret-volume
              secret:
                secretName: mysql-backup-s3-secret
          restartPolicy: Never
parameters:
  - name: AWS_ACCESS_KEY_ID
    description: 'AWS Access Key ID'
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: 'AWS Secret Access Key'
    required: true
  - name: AWS_S3_BUCKET_NAME
    description: 'Name of an existing Amazon S3 bucket where backups are to be pushed'
    required: true
  - name: MYSQL_HOST
    description: 'MySQL host to target'
    required: true
  - name: MYSQL_USER
    description: 'MySQL user to perform the backup'
    required: true
  - name: MYSQL_PASSWORD
    description: 'MySQL user password'
    required: true
  - name: GPG_RECIPIENT
    description: 'GPG recpient name to be used to encrypt the database archive'
    required: true
  - name: GPG_PUBLIC_KEY
    description: 'GPG public key content (base64 encoded)'
    required: true
  - name: GPG_TRUST_MODEL
    description: 'GPG encryption trust model, defaults to "always"'
    value: 'always'
