---
apiVersion: v1
kind: Template
metadata:
  name: mysql-backup-s3-cronjob-template
  annotations:
    description: 'Cron job for backing up MySQL data to Amazon S3'
objects:
  - apiVersion: batch/v2alpha1
    kind: CronJob
    metadata:
      name: mysql-backup-s3-cronjob
    spec:
      schedule: ${CRON_SCHEDULE}
      jobTemplate:
        spec:
          template:
            metadata:
              name: mysql-backup-s3-cronjob
            spec:
              containers:
                - name: mysql-backup-s3-cronjob
                  image: 'docker.io/rhmap/backups:latest'
                  command:
                    - 'bash'
                    - '-c'
                    - '/opt/rh/scripts/mysql/backup-s3.sh ${MYSQL_HOST} ${MYSQL_USER} ${MYSQL_PASSWORD} ${AWS_S3_BUCKET_NAME}'
                  env:
                    - name: AWS_ACCESS_KEY_ID
                      value: ${AWS_ACCESS_KEY_ID}
                    - name: AWS_SECRET_ACCESS_KEY
                      value: ${AWS_SECRET_ACCESS_KEY}
              restartPolicy: Never
parameters:
  - name: AWS_ACCESS_KEY_ID
    description: 'AWS Access Key ID'
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: 'AWS Secret Access Key'
    required: true
  - name: AWS_S3_BUCKET_NAME
    description: 'Name of an existing Amazon S3 bucket where backups are to be pushed'
    required: true
  - name: CRON_SCHEDULE
    description: 'Job schedule in Cron Format [Default is everyday at 2am]'
    value: '0 2 * * *'
  - name: MYSQL_HOST
    description: 'MySQL host to target'
    required: true
  - name: MYSQL_USER
    description: 'MySQL user to perform the backup'
    required: true
  - name: MYSQL_PASSWORD
    description: 'MySQL user password'
    required: true
